### ISSUE TITLE
won't play

### ISSUE THREAD

**Issue by dawl1** [arcticmatt/online-omnichord#3]
i love this so much! I'm super new to coding so idk how to fix this but it won't play, no sound will come out, it will load but not play! any tips?

**Comment by arcticmatt** [comment]
Hey @dawl1, glad you like it! Have you read over the instructions at http://www.onlineomnichord.com/info? Also, what browser are you using?

**Comment by dawl1** [comment]
i have! i was using safari till I realised that you said that won't work, tried chrome nothing there either! i even tried on my iPad same result I'm not sure whats happening, also.a bit unrelated but would there be anyway this could be converted into an instrument/vst/plug-in? id love to beable to directly record from it to use! :)

**Comment by arcticmatt** [comment]
Unfortunately it doesn't work on iPads (or phones) because you need the keyboard to play it. If you're using Chrome it should work, make sure you're playing it with your keyboard as opposed to clicking the buttons.

> a bit unrelated but would there be anyway this could be converted into an instrument/vst/plug-in? id love to beable to directly record from it to use! :)

That would be super cool! I also have no idea how to do that haha.

**Comment by dawl1** [comment]
okay thank you! ill give it a go on my MacBook and let you know! (and same, if you ever get around to finding out, I think decentsampler would be good its free ! you could probably sell it, or add it to the pianobook.compublic library its a super saught after instrument !:) )

**Comment by dawl1** [comment]
Got it! thank you i think my mac was just acting up!
